spencergilbert/update and pin rust
krator-rs/krator pull request #67
Opened 2022-04-13 20:16 UTC by spencergilbert

Hi! I started poking around krator and ran into a few issues with the Rust version and the UI tests. This should resolve them, and I fixed the naming of the CI steps noted here: https://github.com/krator-rs/krator/pull/51#discussion_r716937482

- Update and pin rust to 1.60, reblessing UI tests
- Fix step names for UI test job

2022-04-13 22:21 UTC, kflansburg requested changes
Appreciate the update to `1.60`. I'm not sure that we want to pin the Rust version though, we've historically tried to always support `stable`. Based on [rustup Docs](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file), it seems like pinning is a special case, rather than best practice.

2022-04-13 22:34 UTC, spencergilbert commented
> Appreciate the update to `1.60`. I'm not sure that we want to pin the Rust version though, we've historically tried to always support `stable`. Based on [rustup Docs](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file), it seems like pinning is a special case, rather than best practice.

Cool - I'll roll that back and mess with the tests again, they were fine locally but I'm not super familiar with the compiled tests there.

I was also looking at upgrading deps, particularly `kube` to get token rotation support - if y'all are interested in upgrading some/all of the crates.

2022-04-13 22:49 UTC, kflansburg commented
> Cool - I'll roll that back and mess with the tests again, they were fine locally but I'm not super familiar with the compiled tests there.
> 
> I was also looking at upgrading deps, particularly `kube` to get token rotation support - if y'all are interested in upgrading some/all of the crates.

Thanks. Would definitely be interested in a `kube` upgrade.

2022-04-14 13:09 UTC, kflansburg commented
Changes included in #68

2022-04-14 13:09 UTC, closed without merging